#!/usr/bin/env bash
# ASDD - post/update the intake feedback comment. Runs ONLY in the write-scoped intake-feedback workflow,
# never in the read-only intake job.
#
# It reads intake.json (the verdict + the ASDD-GENERATED problem strings) and meta.env (pr_number) as
# DATA. It NEVER echoes untrusted PR content: the problems are deterministic strings produced by
# intake-check.sh from the config and the checks, not text copied from the PR. It maintains exactly one
# comment per PR (found by a hidden marker) so a contributor fixing and re-pushing sees the list update
# in place rather than a wall of comments, and it clears to a "passing" note once intake passes. It posts;
# it never merges.
#
# Usage: post-intake-feedback.sh <workdir with intake.json + meta.env>
# Env: GH_TOKEN, REPO (owner/name).
set -euo pipefail

WORK="${1:?usage: post-intake-feedback.sh <workdir>}"
: "${GH_TOKEN:?GH_TOKEN required}"
: "${REPO:?REPO (owner/name) required}"

[ -f "$WORK/intake.json" ] || { echo "post-intake-feedback: no intake.json; nothing to do"; exit 0; }
# shellcheck disable=SC1091
set -a; . "$WORK/meta.env"; set +a   # pr_number
[[ "${pr_number:-}" =~ ^[0-9]+$ ]] || { echo "post-intake-feedback: invalid pr_number" >&2; exit 1; }

MARKER="<!-- asdd-intake-feedback -->"
PASSED="$(jq -r '.passed' "$WORK/intake.json")"

# The id of an existing feedback comment on this PR, if any (matched by the hidden marker).
CID="$(gh api "repos/${REPO}/issues/${pr_number}/comments" --paginate \
  | jq -r --arg m "$MARKER" 'map(select(.body != null and (.body|contains($m)))) | (.[0].id // empty)')"

if [ "$PASSED" = "true" ]; then
  # Nothing to nag about. Only touch a comment if we previously left one, so green PRs stay quiet.
  [ -n "$CID" ] || { echo "post-intake-feedback: intake passed and no prior comment; quiet."; exit 0; }
  BODY="${MARKER}"$'\n'"**ASDD intake: passing.** Disclosure, DCO sign-off, one lane tag, and a spec are all present. Thanks for fixing it up."
  gh api "repos/${REPO}/issues/comments/${CID}" -X PATCH -f body="$BODY" >/dev/null
  echo "post-intake-feedback: updated the comment to passing."
  exit 0
fi

PROBS="$(jq -r '.problems[]? | "- " + .' "$WORK/intake.json")"
BODY="$(cat <<MD
${MARKER}
**ASDD intake is not passing yet.** Fix these, then push again:

${PROBS}

<sub>Intake is the deterministic PR-admission gate; it runs before review, and review does not run until it passes. Generated by [ASDD](https://github.com/OneHillAI/ASDD).</sub>
MD
)"

if [ -n "$CID" ]; then
  gh api "repos/${REPO}/issues/comments/${CID}" -X PATCH -f body="$BODY" >/dev/null
  echo "post-intake-feedback: updated the comment with the current problems."
else
  gh api "repos/${REPO}/issues/${pr_number}/comments" -f body="$BODY" >/dev/null
  echo "post-intake-feedback: posted the feedback comment."
fi
