#!/usr/bin/env bash
# ASDD - post the advisory review comment. Runs ONLY in the write-scoped publish workflow.
#
# Consumes review.json as DATA and posts an advisory comment via the GitHub API (a fixed action, not a
# shell-exec of model output). It posts; it never merges. Disclosure is baked into the comment header.
#
# Usage: post-review.sh <review.json>
# Env: GH_TOKEN, REPO (owner/name).
set -euo pipefail

REVIEW="${1:?usage: post-review.sh <review.json>}"
: "${GH_TOKEN:?GH_TOKEN required}"
: "${REPO:?REPO (owner/name) required}"

PR="$(jq -r '.pr_number' "$REVIEW")"
[[ "$PR" =~ ^[0-9]+$ ]] || { echo "post-review: invalid pr_number" >&2; exit 1; }

MODE="$(jq -r '.mode // "live"' "$REVIEW")"
REC="$(jq -r '.recommendation // "comment"' "$REVIEW")"
SUMMARY="$(jq -r '.summary // ""' "$REVIEW")"

LENSES="$(jq -r '
  (.lenses // []) | map(
    "### " + (.lens|ascii_upcase) + " - " + (.verdict // "n/a") + "\n" +
    ((.findings // []) | if length==0 then "_No findings._\n"
      else map("- " + (.severity // "note") + ": " + (.message // .)) | join("\n") + "\n" end)
  ) | join("\n")
' "$REVIEW")"

NOTE=""
[ "$MODE" = "dry-run" ] && NOTE=$'\n> **NOT A REVIEW.** No model is connected, so the review agent did not run. This is a placeholder, not a judgement: do not approve it as if the change were reviewed. Only the deterministic gates (intake, the security scan) are real here. Connect a runtime (`ASDD_MODEL_URL` variable + `ASDD_RUNTIME_TOKEN` secret), then re-run for a real review. `asdd connect-check` reports which agents are connected.\n'

BODY="$(cat <<MD
**ASDD review - advisory** (recommendation: \`${REC}\`)

> Produced by an automated agent under human direction. Advisory only: a human approves and merges.
> Nothing here merges automatically.
${NOTE}
${SUMMARY}

${LENSES}

---
<sub>Generated by the [ASDD](https://github.com/OneHillAI/ASDD) advisory review. Mode: \`${MODE}\`.</sub>
MD
)"

# Public-artefact hygiene. The summary and lens text are written by a model, and this comment is public on
# an open repository. Normalise en and em dashes to a plain hyphen so generated review text matches the
# project's writing standard; the docs lint does not cover comments, so nothing else would catch it.
# Fail-safe: if python3 is unavailable the comment still posts, unchanged.
if command -v python3 >/dev/null 2>&1; then
  BODY="$(printf '%s' "$BODY" | python3 -c 'import sys; sys.stdout.write(sys.stdin.read().replace("\u2013", "-").replace("\u2014", "-"))')" || true
fi

echo "post-review: posting advisory comment to ${REPO}#${PR} (mode=${MODE}, rec=${REC})"
gh api "repos/${REPO}/issues/${PR}/comments" -f body="$BODY" >/dev/null
echo "post-review: done"
